
import razredi.Vprasanje;

import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import jdk.nashorn.internal.ir.RuntimeNode.Request;
import povezava.Povezava;

/**
 * Servlet implementation class 
 */
@WebServlet("/eksperiment.xls")
public class ToExcel extends HttpServlet {
	private static final long serialVersionUID = 1L;
	
       
    /**
     * @see HttpServlet#HttpServlet()
     */
   
	

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	

	public void service(HttpServletRequest req, HttpServletResponse res) {
		try {
			int id=Integer.parseInt(req.getParameter("a"));
			res.setContentType("application/vnd.ms-excel");
			Povezava p = new Povezava();
			List<Vprasanje> a=p.selectVprasanja(id);
			res.setCharacterEncoding("Windows-1250");
			res.getWriter().println("TIP\tCAS\tPRAVILNA BARVA\tVNESENA BARVA\tTEKST\tPRAVILNOST\tSPOL\tSIFRA\tSTAROST");
			
			for (Vprasanje v:a){
				res.getWriter().println(v.getTip()+"\t"+v.getCas()+"\t"+v.getMojabarva()+"\t"+v.getVnesenabarva()+"\t"+ v.getTekst()+"\t"+v.isPravilnost()+"\t"+v.getSpol()+"\t"+v.getSifra()+"\t"+v.getStarost());
			}
			res.getWriter().println("Generated by Florijan Klezin, Špela Pečnik, Miha Kebe, Denis Vodišek");

		} catch (Exception e) {
		}
	} 
	
	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		
	}

}
